account/urls.py
from django.urls import path

from account.views import (
	account_view,
	edit_account_view,
)

app_name = 'account'

urlpatterns = [

	path('<user_id>/', account_view, name="view"),
	path('<user_id>/edit/', edit_account_view, name="edit"),
	
]

chat/urls.py
from django.urls import path

from chat.views import(
	private_chat_room_view,
	create_or_return_private_chat,
)

app_name = 'chat'

urlpatterns = [
	path('', private_chat_room_view, name= 'private-chat-room'),
	path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),

]

guacochat/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import include


from personal.views import (
    home_screen_view
)

from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,
)

urlpatterns = [
    path('', home_screen_view, name='home'),
    path('account/', include('account.urls', namespace = 'account')),
    path('admin/', admin.site.urls),
    path('friend/', include('friend.urls', namespace = 'friend')),
    path('chat/', include('chat.urls', namespace = 'chat')),
    path('login/', login_view, name = "login"),
    path('logout/', logout_view, name = "logout"),
    path('register/', register_view, name = "register"),
    path('search/', account_search_view, name = "search"),

 # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
    name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
    name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
    name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
    name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/base_css.html
<style type="text/css">
    head{
        color: #FAD1FF;
        font-family: "fangsong";
        font-weight: 380;
    }

    footer{
        font-family: "fangsong";
        font-weight: 380;
    }
    body{
        background-color: #ADD8E6;
        font-family: "fangsong";
        font-weight: 380;
    }

    :root {
        --main-background-color: #FAD1FF;
        --dark-background-color: #a2a2a2;
        --seccondary-text-color: #808080;
        --light-primary-text-color: #0080ff;
    }
</style>

templates/snippets/base_js.html
<script type="text/javascript">
	
	function preloadCallback(src, elementId){
		var img = document.getElementById(elementId)
		img.src = src
	}

	function preloadImage(imgSrc, elementId){
		// console.log("attempting to load " + imgSrc + " on element " + elementId)
		var objImagePreloader = new Image();
		objImagePreloader.src = imgSrc;
		if(objImagePreloader.complete){
			preloadCallback(objImagePreloader.src, elementId);
			objImagePreloader.onload = function(){};
		}
		else{
			objImagePreloader.onload = function() {
				preloadCallback(objImagePreloader.src, elementId);
				//    clear onLoad, IE behaves irratically with animated gifs otherwise
				objImagePreloader.onload=function(){};
			}
		}
	}

	/*
		Build a <p> for messages using markdown
		https://github.com/markdown-it/markdown-it
	*/
	function validateText(str)
	{
		var md = window.markdownit({
			highlight: function (str, lang) {
				if (lang && hljs.getLanguage(lang)) {
					try {
						return '<pre class="hljs"><code>' +
							hljs.highlight(lang, str, true).value +
							'</code></pre>';
					} catch (__) {}
				}
				return '<pre class="hljs"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
			},
			linkify: true,
		});
		var result = md.render(str);
		return result
	}
	
</script>

templates/snippets/footer.html
<style type="text/css">
    .footer{
        min-height: 100px;
    }
</style>
<div class="d-flex flex-row align-items-center footer bg-blue shadow-lg mt-4">
    <p class="m-auto"> Web Chat </p>
</div>

templates/snippets/header.html
{% load static %}
<style type="text/css">
.chat-dropdown-header:hover{
    cursor: pointer;
    background: var(--main-background-color);

}
.chat-dropdown-header{
    color: var(--light-primary-text-color);

}
</style>

<div class="d-flex p-3 px-md-4 mb-4 bg-blue border-bottom shadow-sm">
    
    <div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-cemter">

        <!-- c1 -->
        <h5 class="mr-3 font-wight-normal justify-content-start">
            <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
        </h5>

        <!-- c2 -->
        <form class="search-bar justify-content-start" onsubmit="return executeQuery();">
        <input type="text" class="form-control" name="q" id="id_q_large" placeholder="Search...">
        </form>

        <!-- c3 -->
        <div class="d-flex flex-row-reverse flex-grow-1">
            <nav class="">
            {% if request.user.is_authenticated %}
                <div class="dropdown dropleft show p-2">
                    <div class="d-flex flex-row">
                        <!-- Chat Notifications -->
                        <div class="btn-group dropleft">
                            <div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3" id="id_chat_notification_dropdown_toggle" data-toggle="dropdown">
                                <span id="id_chat_notifications_count" class="notify-badge"></span>
                                <span class="d-flex material-icons notifications-material-icon m-auto align-items-center">chat</span>
                                <div class="dropdown-menu scrollable-menu" aria-labelledby="id_chat_notification_dropdown_toggle" id="id_chat_notifications_container">
                                </div>
                            </div>
                        </div>
                        <!-- General Notification -->
                        <div class="btn-group dropleft">
                            <div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3" id="id_notification_dropdown_toggle" data-toggle="dropdown" >
                                <span id="id_general_notifications_count" class="notify-badge"></span>
                                <span class="d-flex material-icons notifications-material-icon m-auto align-items-center">notifications</span>
                                <div class="dropdown-menu scrollable-menu" aria-labelledby="id_notification_dropdown_toggle" id="id_general_notifications_container">					
                                </div>
                            </div>
                        </div>
                        <!-- Account -->
                        <div class="btn-group dropleft">
                            <img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" alt="logo" width="40" height="40">
                            <div class="dropdown-menu" aria-labelledby="id_profile_links">
                                <a class="dropdown-item" href="{% url 'account:view' user_id=request.user.id %}">Account</a>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </div>
                    </div>
                    
                </div>
                {% else %}
                    <a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
                    <a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
                {% endif %}	
            </nav>
        </div>
    </div>
    <!-- END MEDIUM+ SCREENS -->

	<!-- SMALL SCREENS -->
	<div class="d-flex d-md-none flex-column my-auto align-items-center">

        <!-- r1 -->
		<h5 class="font-weight-normal">
		    <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		</h5>

        <!-- r2 -->
		<form class="search-bar justify-content-start" onsubmit="return executeQuery();">
			<input type="text" class="form-control" name="q" id="id_q_small" placeholder="Search...">
		</form>

        <!-- r3 -->
		<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
				<div class="dropdown dropleft p-2 mt-2">
					<div class="d-flex flex-row">
						<div class="btn-group dropleft">
							<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{request.user.profile_image.url}}" alt="logo" width="40" height="40">
							<div class="dropdown-menu" aria-labelledby="id_profile_links">
								<a class="dropdown-item" href="{% url 'account:view' user_id=request.user.id  %}">Account</a>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
							</div>
						</div>
					</div>
				</div>
				{% else %}
					<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
					<a class="btn btn-outline-primary m-2" href="{% url 'register' %}">Register</a>
				{% endif %}	
			</nav>
	  	</div>
	</div>
	<!-- END SMALL SCREENS -->
</div>

<script type="text/javascript">
    setupChatDropdownHeader()

    function executeQuery(){
        var query = document.getElementById("id_q_small").value;
        if(query == ""){
            query = document.getElementById("id_q_large").value;
        }
        window.location.replace("{% url 'search' %}?q=" + query)
        return false
    }
    function setupChatDropdownHeader(){
		var notificationContainer = document.getElementById("id_chat_notifications_container")

		if(notificationContainer != null){

			var div = document.createElement("div")
			div.classList.add("chat-dropdown-header", "d-flex", "flex-row", "justify-content-end", "m-auto", "align-items-end")
			div.addEventListener("click", function(e){
				var url = "{% url 'chat:private-chat-room' %}"
				chatRedirect(url)
			})

			span1 = document.createElement("span")
			span1.classList.add("mr-2")
			span1.innerHTML = "Go to chat"
			div.appendChild(span1)

			span2 = document.createElement("span")
			span2.classList.add("material-icons", "mr-2")
			span2.innerHTML = "open_with"
			div.appendChild(span2)
			notificationContainer.appendChild(div)
		}
	}

	function chatRedirect(url){
		window.location.href = url
	}
</script>